### ISSUE TITLE
The Merging QR-code / QR-code scanner app from ZXing Team can only be used on old Android versions in Mergin.

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [MerginMaps/mergin#86] opened 2023-06-07 15:16 UTC
The Merging QR-code / QR-code scanner app from ZXing Team can only be used on old Android versions in Mergin.
It does not work in Mergin on new Android versions because the QR code scanner app from ZXing Team is not available in the Play store.

Is there already a solution for this?

**Comment by PeterPetrik** [comment] 2023-07-25 07:24
duplicate of https://github.com/MerginMaps/input/issues/2669

**Closed by PeterPetrik** 2023-07-25 07:24 UTC
