### ISSUE TITLE
Projects visible by all users

### ISSUE THREAD

**Issue by arno974** [MerginMaps/mergin#84] opened 2023-06-05 06:42 UTC
Hi,

I'm surprised because the projects created by a user are visible to everyone. As suggested in this ticket (https://github.com/MerginMaps/mergin/issues/81), I change in `.prod.env ` the default parameters to :

```
GLOBAL_READ=False
GLOBAL_WRITE=False
GLOBAL_ADMIN=False
```
Then I've reloaded the service with `docker-compose up --force-recreate -d`. 

But even after these changes, projects are still available to everyone. 

Do you know what I must change to be sure that a project can be visible only if a user share it with someone else ?

Thanks for your help,

Arnaud

**Comment by PeterPetrik** [comment] 2023-08-07 08:12
duplicate of https://github.com/MerginMaps/mergin/issues/101

**Closed by PeterPetrik** 2023-08-07 08:12 UTC
